module "message_queue" {
  #source              = "git::https://github.com/Nitintothenew/terraform-aws-queue.git"
  source           = "../"
  ec2_subnet_id = "subnet-0653cf0794e67394e"
  key_name = "default-dev"
  vpc_id  = "vpc-0bdd7143882d1738f"
  instance_type = "t3a.medium"
  kms_key_id              = "5a9d8a04-28a5-422b-9955-4527702f7c8e"
  disable_api_termination = false
  disable_api_stop        = false
  subnet_ids          = ["subnet-0653cf0794e67394e","subnet-042869d84827c5368"]
  apply_immediately = false
  host_instance_type = "mq.t3.micro"
  deployment_mode    = "ACTIVE_STANDBY_MULTI_AZ"
  storage_type = "efs"
  console_access = true
  publicly_accessible = true
  engine_type = "ActiveMQ"
  engine_version = "5.15.14"
  auto_minor_version_upgrade = false
  activemq_username   = "admin"
  audit_logs = false
  general_logs = false
  worker  = 1
  master  = 1
  create_aws_activemq     = false
  create_aws_ec2_rabbitmq = true
  common_tags         = {
    "Project"     = "ToTheNew",
    "Environment" = "dev"
  }
  project_name_prefix = "TTN"
}
